{{- if .Values.rbac.create -}}
apiVersion: {{ template "virtual-kubelet-saladcloud.rbacApiVersion" . }}
kind: ClusterRoleBinding
metadata:
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "virtual-kubelet-saladcloud.labels" . | nindent 4 }}
  name: {{ include "virtual-kubelet-saladcloud.clusterRoleName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "virtual-kubelet-saladcloud.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
