{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "salad.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
{{ include "salad.labels" . | indent 2 }}
{{ end }}
