blank_issues_enabled: false
contact_links:
  - name: Request support
    url: https://github.com/SaladTechnologies/virtual-kubelet-saladcloud/discussions
    about: Please use GitHub discussions for general chat and community-provided support for the SaladCloud Virtual Kubelet.
