{{- /*
Copyright Salad Technologies, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  {{- if (or .Values.commonAnnotations .Values.secret.annotations) }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "virtual-kubelet-saladcloud.labels" . | nindent 4 }}
    {{- with .Values.secret.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ default (include "virtual-kubelet-saladcloud.fullname" .) .Values.secret.name }}
  namespace: {{ include "virtual-kubelet-saladcloud.namespace" . | quote }}
type: Opaque
data:
  salad-cloud-api-key: {{ .Values.salad.apiKey | b64enc | quote }}
{{- end }}
