{{- /*
Copyright Salad Technologies, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if (or .Values.commonAnnotations .Values.serviceAccount.annotations) }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "virtual-kubelet-saladcloud.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "virtual-kubelet-saladcloud.serviceAccountName" . }}
  namespace: {{ include "virtual-kubelet-saladcloud.namespace" . | quote }}
automountServiceAccountToken: false
{{- end }}
